
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: portfolio-backend:v2.0
    container_name: portfolio-backend-prod
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=core_portfolio.settings
    networks:
      - portfolio-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: portfolio-frontend:v2.0
    container_name: portfolio-frontend-prod
    ports:
      - "80:3000"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - portfolio-network
    restart: always

networks:
  portfolio-network:
    driver: bridge
