# Generated by Django 6.0 on 2026-01-25 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_authormodel_is_active_blogpostmodel_is_active'),
        ('portfolio', '0003_categorymodel_portfolio_c_name_152cab_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostmodel',
            old_name='title',
            new_name='BlogPostModel',
        ),
        migrations.AddIndex(
            model_name='authormodel',
            index=models.Index(fields=['user', 'display_name'], name='blog_author_user_id_a1f5da_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpostmodel',
            index=models.Index(fields=['is_featured'], name='blog_blogpo_author__e93f08_idx'),
        ),
    ]
