# Generated by Django 6.0 on 2026-01-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_title_blogpostmodel_blogpostmodel_and_more'),
        ('portfolio', '0003_categorymodel_portfolio_c_name_152cab_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blogpostmodel',
            name='blog_blogpo_author__e93f08_idx',
        ),
        migrations.AddIndex(
            model_name='blogpostmodel',
            index=models.Index(fields=['is_featured'], name='blog_blogpo_author__1b0526_idx'),
        ),
    ]
