# Generated by Django 6.0 on 2026-01-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicefeaturemodel',
            index=models.Index(fields=['service'], name='services_se_service_511b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemodel',
            index=models.Index(fields=['is_featured', 'is_active'], name='services_se_is_feat_22ca02_idx'),
        ),
    ]
