# Generated by Django 6.0 on 2026-01-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_categorymodel_is_active_portfolioitemmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categorymodel',
            index=models.Index(fields=['name', 'type', 'parent'], name='portfolio_c_name_152cab_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliofeaturemodel',
            index=models.Index(fields=['portfolio_item'], name='portfolio_p_portfol_c2f378_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioimagemodel',
            index=models.Index(fields=['is_primary'], name='portfolio_p_is_prim_0e6ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitemmodel',
            index=models.Index(fields=['title'], name='portfolio_p_title_4e6c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='tagmodel',
            index=models.Index(fields=['name', 'slug'], name='portfolio_t_name_16dffe_idx'),
        ),
    ]
