# Generated by Django 6.0 on 2026-01-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolioimagemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliofeaturemodel',
            name='feature_skill',
            field=models.CharField(choices=[('seo', 'SEO EXPERT'), ('full stack developer', 'Full Stack Developer'), ('web developer', 'WEB DEVELOPER'), ('cyber security expert', 'CYBER SECURITY EXPERT')], default='seo', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliofeaturemodel',
            name='feature_text2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliofeaturemodel',
            name='greet_message',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliofeaturemodel',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/%Y/%m/resume/'),
        ),
    ]
