# Generated by Django 6.0 on 2026-01-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_categorymodel_portfolio_c_name_152cab_idx_and_more'),
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testimonialmodel',
            index=models.Index(fields=['is_active', 'rating', 'is_featured'], name='testimonial_is_acti_312606_idx'),
        ),
    ]
