# Generated by Django 6.0 on 2026-01-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_educationmodel_is_active_skillmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='educationmodel',
            index=models.Index(fields=['degree_title'], name='resume_educ_degree__0ac51c_idx'),
        ),
        migrations.AddIndex(
            model_name='skillmodel',
            index=models.Index(fields=['category'], name='resume_skil_categor_b9103a_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperiencemodel',
            index=models.Index(fields=['is_current'], name='resume_work_is_curr_0364c9_idx'),
        ),
    ]
