# Generated by Django 6.0 on 2026-01-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0004_sitesettingmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactinfomodels',
            index=models.Index(fields=['is_active'], name='site_config_is_acti_0967ab_idx'),
        ),
        migrations.AddIndex(
            model_name='externalprofilemodel',
            index=models.Index(fields=['is_active'], name='site_config_is_acti_b8e41b_idx'),
        ),
        migrations.AddIndex(
            model_name='funfactmodel',
            index=models.Index(fields=['is_active'], name='site_config_is_acti_5b06a5_idx'),
        ),
        migrations.AddIndex(
            model_name='partnermodel',
            index=models.Index(fields=['is_active'], name='site_config_is_acti_45530a_idx'),
        ),
        migrations.AddIndex(
            model_name='planfeaturemodel',
            index=models.Index(fields=['is_active', 'is_included'], name='site_config_is_acti_b611df_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingplanmodel',
            index=models.Index(fields=['is_active', 'is_featured'], name='site_config_is_acti_17bc74_idx'),
        ),
        migrations.AddIndex(
            model_name='sitesettingmodel',
            index=models.Index(fields=['is_active'], name='site_config_is_acti_5f7d81_idx'),
        ),
        migrations.AddIndex(
            model_name='sociallinkmodel',
            index=models.Index(fields=['is_active'], name='site_config_is_acti_786beb_idx'),
        ),
    ]
